# Generated by Django 4.2.17 on 2024-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='original_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='original_title',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='property',
            name='rewritten_title',
            field=models.TextField(default='Not rewritten'),
        ),
        migrations.AlterModelTable(
            name='property',
            table='rewrite_property_info',
        ),
    ]
