# Generated by Django 4.2.17 on 2024-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyratingreview_propertysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=255)),
                ('positionName', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roomType', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotels',
                'managed': False,
            },
        ),
    ]
